version: '3'

networks:
  laravel:

volumes:
  node_modules:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./src/:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/html/
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
    networks:
      - laravel

  redis:
    image: redis:alpine
    volumes:
      - ./redis:/data/
    networks:
      - laravel

  node:
    image: node:20-alpine
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - node_modules:/var/www/html/node_modules
    ports:
      - "5173:5173"
    networks:
      - laravel
    command: tail -f /dev/null
    depends_on:
      - php