version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./src/:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
      
  mysql:
   image: mariadb:10.3
   restart: unless-stopped
   tty: true
   ports:
    - "3309:3306"
   volumes:
    - ./mysql:/var/lib/mysql
   environment:
     MYSQL_DATABASE: homestead
     MYSQL_USER: homestead
     MYSQL_PASSWORD: secret
     MYSQL_ROOT_PASSWORD: secret
     SERVICE_TAGS: dev
     SERVICE_NAME: mysql
   networks:
     - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/html/
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
    - "9000:9000"
    networks:
    - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - 8080:80
    links:
    - mysql
    environment:
      PMA_HOST: mysql
    networks:
    - laravel

  redis:
    image: redis:alpine
    volumes:
      - ./redis:/data/
    networks:
      - laravel